input_data:   ['/data/galucia/lithium_local/MC_merged/LHC25a4.root',
                ]
tree_name:    'O2he3hadtable'
mode:         'DF'
output_file:  'output/efficiency.root'

selections:     [
                # quality cuts
                 #'((fDeltaPhi/0.006)*(fDeltaPhi/0.006) + (fDeltaEta/0.012)*(fDeltaEta/0.012) > 1)',
                 
                 #'(((fChi2TPCHe3 > 0.5) || (fIs23 == false)) && (fChi2TPCHe3 < 4))', # not to apply on mc
                 
                 '((fChi2TPCHad < 4))',
                 '(std::abs(fEtaHe3) < 0.9)',
                 '(std::abs(fEtaHad) < 0.9)',
                 '(fNClsTPCHe3 > 110)',
                 
                 '((fPtHe3 < 2.5) || (fPIDtrkHe3 == 7))',
                 '((fPIDtrkHe3 == 6) || (fPIDtrkHe3 == 7) || (fPIDtrkHe3 == 8))',
                 #'((fPIDtrkHe3 == 7))',
                 '((-2. < fNSigmaTPCHe3) && (fNSigmaTPCHe3 < 2.))',
                 '(std::abs(fNSigmaDCAxyHe3) < 3)',
                 '(std::abs(fNSigmaDCAzHe3) < 3)',
                 #'(fClusterSizeCosLamHe3 > 4)',
                 ##'(fNSigmaITSHe3 > -1.5)',  ## ITS pid not implemented in mc
                 '(fMassTOFHe3 > 2 || fMassTOFHe3 < 0)',

                 '(std::abs(fNSigmaTPCHad) < 2)',
                 #'(std::abs(fNSigmaTPCHadPr) < 2)',
                 '((std::abs(fPtHad) < 0.8) || (std::abs(fNSigmaTOFHad) < 2))',  # TOF hard cut
                 #'((std::abs(fPtHad) < 0.8) || (std::abs(fNSigmaTOFHad) < 2) || (fNSigmaTOFHad < -9.9))', # TOF veto
                 ##'(fNSigmaITSHad > -2.)', ## ITS pid not implemented in mc
                 '(std::abs(fNSigmaDCAxyHad) < 3)',
                 '(std::abs(fNSigmaDCAzHad) < 3)',
                ]
